### ISSUE TITLE
Package manager icons

### ISSUE THREAD

**Issue by Princesseuh** [HiDeoo/starlight-package-managers#5]
### Is your feature request related to a problem?

N/A

### Describe the solution you'd like

It'd be cool if it'd show icons next to the package managers, like on the Biome website https://biomejs.dev/guides/getting-started/#installation

### Describe alternatives you've considered

Well, not having icons, but it's not as nice, right

**Comment by HiDeoo** [comment]
Oh, I love the idea, this looks super great!

Internally, this component relies on the Starlight built-in [`<Tabs>` component](https://starlight.astro.build/guides/components/#tabs) and only builds on top of it to add syncing between the tabs. Unfortunately, the built-in component doesn't support this feature and only accepts a basic string as a tab label.

Replacing the built-in component with a custom one that would literally be 90% the same just to render an extra icon seems meh, so instead I just opened a new [feature request](https://github.com/withastro/starlight/discussions/1453) in Starlight to add a new `icon` prop to the `<TabItem>` component that would accept the name of an icon from the Starlight icon set and render it next to the label.

If this is something of interest (I personally really like the idea), this would be a fairly easy addition, and I already have an unrelated opened [PR](https://github.com/withastro/starlight/pull/1308) that adds icons for `npm`, `yarn`, and `pnpm`. We could also add `bun` too and then this issue would be as good as solved.

**Comment by HiDeoo** [comment]
All the pre-requisites Starlight PRs have been merged and released and the feature is now available in the new [`v0.4.0`](https://github.com/HiDeoo/starlight-package-managers/releases/tag/v0.4.0) of the package.

<img width="750" alt="image" src="https://github.com/HiDeoo/starlight-package-managers/assets/494699/3c55eeec-0781-4a3a-91d9-7c52db362e81">

Thanks again for the great feature request :raised_hands:

**Comment by Princesseuh** [comment]
Really cool, awesome work!
